# Generated by Django 4.1.7 on 2023-03-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleruser',
            name='birth_date',
        ),
    ]
