# Generated by Django 4.1.7 on 2023-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_selleruser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
