# Generated by Django 4.1.7 on 2023-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
