# Generated by Django 4.1.7 on 2023-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
    ]
