# Generated by Django 4.1.7 on 2023-05-02 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zip code must be 5 digits in format 12345 or 12345-6789', regex='^\\d{5}(?:[-\\s]\\d{4})?$')]),
        ),
    ]
