# Generated by Django 4.1.7 on 2023-04-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_seller_alter_order_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_status",
            field=models.BooleanField(default=False),
        ),
    ]
