# Generated by Django 4.1.7 on 2023-04-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerprofile_is_approved'),
        ('order', '0005_orderitem_item_name_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buyerUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_order_item', to='accounts.buyerprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sellerUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_order_item', to='accounts.sellerprofile'),
        ),
    ]
